urlTemplateLinkProject/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path , include
from simple_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('simpleApp/',include('simple_app.urls'))
]

urlTemplateLinkProject/learning_templates/simple_app/urls.py
from django.urls import path , include
from simple_app import views

# TEMPLATE TAGGING

app_name = 'simple_app'

urlpatterns = [
    path('base/',views.base,name='base'),
    path('other/',views.other,name='other'),
    path('relative/',views.base,name='relative'),
] 

urlTemplateLinkProject/learning_templates/simple_app/models.py
from django.db import models

# Create your models here.

urlTemplateLinkProject/learning_templates/simple_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    dict = {'text':'This is my country','number':100}
    return render(request,'simpleApp/index.html',dict)
    
def base(request):
    return render(request,'simpleApp/base.html')
    
def other(request):
    return render(request,'simpleApp/other.html')
    
def relative(request):
    return render(request,'simpleApp/relative_url.html')

urlTemplateLinkProject/learning_templates/templates/simpleApp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'simple_app:other' %}">Other</a>
                </li>
                
            </ul>
        </div>
    </nav>

    {% block body_block %}

    {% endblock %}



    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
</body>

</html>

urlTemplateLinkProject/learning_templates/templates/simpleApp/index.html
<!DOCTYPE html>
{% extends 'simpleApp/base.html' %}

    {% block body_block %}
        <br>
        <br>
        <p>THis is index template</p>

        <h4>{{ text|upper }}</h4>
        <h4>{{ text|cut:'my' }}</h4>
        <h4>{{ text|getlen }}</h4>
        <h4>{{ number|add:'99' }}</h4>

        <!-- <p>{% autoescape off %}{{ cal }}{% endautoescape %}</p> -->
        
        <!-- <a href="{% url 'simple_app:other' %}">Go To other File</a><br>
        <a href="{% url 'admin:index' %}">Go To Admin</a><br> -->
    {% endblock %}

urlTemplateLinkProject/learning_templates/templates/simpleApp/other.html
<!DOCTYPE html>
{% extends 'simpleApp/base.html' %}

    {% block body_block %}
        <p>This is the other page </p>
    {% endblock%}

urlTemplateLinkProject/learning_templates/templates/simpleApp/relative_url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <p>THis is relative template</p>

</body>
</html>