cbv_project/advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path,include
from simple_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.IndexView.as_view()),
    path("simple_app/",include('simple_app.urls',namespace='simple_app'))
]

cbv_project/advcbv/simple_app/urls.py
from django.urls import path,include
from simple_app import views

app_name = 'simple_app'

urlpatterns = [
    path('',views.SchoolListView.as_view(),name = 'list'),
    path('<int:pk>/',views.SchoolDetailView.as_view(),name = 'detail'),
    path('create/',views.SchoolCreateView.as_view(),name = 'create'),
    path('update/<int:pk>/',views.SchoolUpdateView.as_view(),name = 'update'),
    path('delete/<int:pk>/',views.SchoolDeleteView.as_view(),name = 'delete'),
    
]

cbv_project/advcbv/simple_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('simple_app:list')
        
    

class Student(models.Model):
    name = models.CharField(max_length=256)
    age  = models.PositiveIntegerField()
    School  = models.ForeignKey(School,related_name='students',on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    

    
    

cbv_project/advcbv/simple_app/views.py
from django.shortcuts import render
from django.views.generic import (View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView)
from django.http import HttpResponse
from . import models
from django.urls import reverse_lazy
# Create your views here.

class IndexView(TemplateView):  
    
    template_name = 'index.html'
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['welcome'] = 'Wlecome to Visit This website  '
        return context 
        

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School
    # school_list


class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'simple_app/school_details.html'

class SchoolCreateView(CreateView):
    fields = ('name','principal','location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name','principal')
    model = models.School
    
class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy('simple_app:list') 
    
    

cbv_project/advcbv/simple_app/templates/simple_app/school_confirm_delete.html
{% extends 'simple_app/simple_app_base.html'%}

{% block body_block %}

    <form method = 'POST'>
        {% csrf_token %}
        <p>Are you sure , you want to delete "{{ school.name }}" ? </p>
        <input type="submit" value="Confirm">
        <a href="{% url 'simple_app:list' %}">Cancel</a>

    </form>

{%endblock%}

cbv_project/advcbv/simple_app/templates/simple_app/school_details.html
{% extends 'simple_app/simple_app_base.html' %}

{% block body_block %}

<h1 class="text-primary">Welcome to School Details Page </h1>
<div class="p-4">
    <h2>School Details</h2>

    <p>Name: {{school_detail.name}}</p>
    <p>Principal: {{school_detail.principal}}</p>
    <p>Location: {{school_detail.location}}</p>

    {% if not school_detail.students.all %}
        
    {% else  %}
        <h2>Students : </h2>
        {% for student in school_detail.students.all %}
        <p>{{student.name}} who is {{student.age}} years old</p>
        {% endfor %}

        
    {% endif %}
    <div class="pt-4 ">
        <a class='button btn-warning p-2' href="{% url 'simple_app:update' school_detail.pk %}">Update</a>
    </div>
</div>



{% endblock %}

cbv_project/advcbv/simple_app/templates/simple_app/school_form.html
{% extends 'simple_app/simple_app_base.html' %}

{% block body_block%}

    {% if not form.instance.pk %}
        <h1 class="text-primary p-2">Create School</h1>
    {% else %}
        <h1>Update School</h1>
    {%endif %}

    <form method = 'POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="submit" >
    </form>

{% endblock %}

cbv_project/advcbv/simple_app/templates/simple_app/school_list.html
{% extends 'simple_app/simple_app_base.html' %}

{% block body_block %}

    <h1>Welcome to a list of all the schools </h1>
    <ol>
        {% for school in schools %}
        <h1><a href="{{school.id}}"><li>{{school.name}}</a></li></h1>
        {% endfor %}
    </ol>

{% endblock %}

cbv_project/advcbv/simple_app/templates/simple_app/simple_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'simple_app:list'%}">Schools<span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>

            <!-- <a class="nav-item nav-link" href="#"></a> -->
           
          </div>
        </div>
      </nav>
    <div class="container">       
        <div class="jumbotron">
            {% block body_block %}

        
            {% endblock %}
        </div>
            
    </div>

    
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

cbv_project/advcbv/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'simple_app:list' %}">Schools<span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>

            <!-- <a class="nav-item nav-link" href="#"></a> -->
           
          </div>
        </div>
      </nav>
    <div class="container">       
        <div class="jumbotron">
            {% block body_block %}

        
            {% endblock %}
        </div>
            
    </div>

    
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

cbv_project/advcbv/templates/index.html
{% extends "base.html" %}

{% block body_block %}

    <h1 class="h1 text-primary">Home Page</h1>
    <h3>{{ welcome }}</h3>

{% endblock %}